export const USER_LOGIN = 'USER_LOGIN';
export const USER_EDIT_PROFILE_TOGGLE = 'USER_EDIT_PROFILE_TOGGLE';
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const MENULIST_FETCH = 'MENULIST_FETCH';

export const INVOICES_FETCH = 'INVOICE_FETCH';
export const INVOICES_SELECT = 'INVOICE_SELECT';
export const INVOICES_PAY = 'INVOICES_PAY';

export const STATEMENTS_FETCH_BY_MONTH = 'STATEMENTS_FETCH_BY_MONTH';
export const STATEMENTS_SHOW = 'STATEMENTS_SHOW';

export const PILLSTORES_FETCH = 'PILLSTORES_FETCH';
